[mypy]
explicit_package_bases = True

[mypy-chromadb.*]
ignore_missing_imports = True

[mypy-slowapi.*]
ignore_missing_imports = True

[mypy-langchain.*]
ignore_missing_imports = True

[mypy-firebase_admin.*]
ignore_missing_imports = True
